{
  "id": "MAL-2024-4789",
  "summary": "Malicious code in azerty123 (PyPI)",
  "details": "\n---\n_-= Per source details. Do not edit below this line.=-_\n",
  "modified": "2024-06-25T13:32:35Z",
  "published": "2024-06-25T13:32:35Z",
  "database_specific": {
    "malicious-packages-origins": [
      {
        "modified_time": "2024-06-25T13:32:35Z",
        "import_time": "2024-06-28T02:48:18.596092511Z",
        "versions": [
          "0.0.1"
        ],
        "id": "RLMA-2024-03569",
        "source": "reversing-labs",
        "sha256": "18b8f76555078995244d717e58e322f8ce59ca2a918354ccc34f32875fcd672b"
      }
    ]
  },
  "affected": [
    {
      "package": {
        "name": "azerty123",
        "ecosystem": "PyPI",
        "purl": "pkg:pypi/azerty123"
      },
      "versions": [
        "0.0.1"
      ],
      "database_specific": {
        "source": "https://github.com/ossf/malicious-packages/blob/main/osv/malicious/pypi/azerty123/MAL-2024-4789.json"
      }
    }
  ],
  "schema_version": "1.6.0",
  "credits": [
    {
      "name": "ReversingLabs",
      "contact": [
        "https://www.reversinglabs.com"
      ],
      "type": "FINDER"
    }
  ]
}