{
  "id": "MAL-2024-5166",
  "summary": "Malicious code in fshec2 (PyPI)",
  "details": "\n---\n_-= Per source details. Do not edit below this line.=-_\n",
  "aliases": [
    "SNYK-PYTHON-FSHEC2-5672158"
  ],
  "modified": "2024-06-28T03:14:54.052228Z",
  "published": "2024-06-25T13:35:38Z",
  "database_specific": {
    "malicious-packages-origins": [
      {
        "modified_time": "2024-06-25T13:35:38Z",
        "import_time": "2024-06-28T02:49:02.22536154Z",
        "versions": [
          "1.0.0"
        ],
        "id": "RLMA-2024-03948",
        "source": "reversing-labs",
        "sha256": "d195cc25d02e51e3b6471b3880ab9b23dd2599eaa6bf4d95bac0a27d1d830d90"
      }
    ]
  },
  "references": [
    {
      "type": "ADVISORY",
      "url": "https://security.snyk.io/vuln/SNYK-PYTHON-FSHEC2-5672158"
    },
    {
      "type": "ARTICLE",
      "url": "https://www.reversinglabs.com/blog/when-python-bytecode-bites-back-who-checks-the-contents-of-compiled-python-files"
    }
  ],
  "affected": [
    {
      "package": {
        "name": "fshec2",
        "ecosystem": "PyPI",
        "purl": "pkg:pypi/fshec2"
      },
      "versions": [
        "1.0.0"
      ],
      "database_specific": {
        "source": "https://github.com/ossf/malicious-packages/blob/main/osv/malicious/pypi/fshec2/MAL-2024-5166.json"
      }
    }
  ],
  "schema_version": "1.6.0",
  "credits": [
    {
      "name": "ReversingLabs",
      "contact": [
        "https://www.reversinglabs.com"
      ],
      "type": "FINDER"
    }
  ]
}