{
  "id": "MAL-2024-5265",
  "summary": "Malicious code in insanepackage21724342386744243242983 (PyPI)",
  "details": "\n---\n_-= Per source details. Do not edit below this line.=-_\n",
  "modified": "2024-06-25T13:36:26Z",
  "published": "2024-06-25T13:36:26Z",
  "database_specific": {
    "malicious-packages-origins": [
      {
        "modified_time": "2024-06-25T13:36:26Z",
        "import_time": "2024-06-28T02:49:14.45228746Z",
        "versions": [
          "1.0.0"
        ],
        "id": "RLMA-2024-04047",
        "source": "reversing-labs",
        "sha256": "10a81f3d409b8499b1c3e651e441288d408532b581fb266d063c00609eb18387"
      }
    ]
  },
  "affected": [
    {
      "package": {
        "name": "insanepackage21724342386744243242983",
        "ecosystem": "PyPI",
        "purl": "pkg:pypi/insanepackage21724342386744243242983"
      },
      "versions": [
        "1.0.0"
      ],
      "database_specific": {
        "source": "https://github.com/ossf/malicious-packages/blob/main/osv/malicious/pypi/insanepackage21724342386744243242983/MAL-2024-5265.json"
      }
    }
  ],
  "schema_version": "1.6.0",
  "credits": [
    {
      "name": "ReversingLabs",
      "contact": [
        "https://www.reversinglabs.com"
      ],
      "type": "FINDER"
    }
  ]
}