{
  "id": "MAL-2024-5133",
  "summary": "Malicious code in feenton (PyPI)",
  "details": "\n---\n_-= Per source details. Do not edit below this line.=-_\n",
  "modified": "2024-06-25T13:35:21Z",
  "published": "2024-06-25T13:35:21Z",
  "database_specific": {
    "malicious-packages-origins": [
      {
        "modified_time": "2024-06-25T13:35:21Z",
        "import_time": "2024-06-28T02:48:58.007380231Z",
        "versions": [
          "1.0"
        ],
        "id": "RLMA-2024-03913",
        "source": "reversing-labs",
        "sha256": "00fcca3d0bae00dcd199cce7de54449b49653a5b9a6c80738655819636af9c81"
      }
    ]
  },
  "references": [
    {
      "type": "WEB",
      "url": "https://github.com/DataDog/malicious-software-packages-dataset"
    }
  ],
  "affected": [
    {
      "package": {
        "name": "feenton",
        "ecosystem": "PyPI",
        "purl": "pkg:pypi/feenton"
      },
      "versions": [
        "1.0"
      ],
      "database_specific": {
        "source": "https://github.com/ossf/malicious-packages/blob/main/osv/malicious/pypi/feenton/MAL-2024-5133.json"
      }
    }
  ],
  "schema_version": "1.6.0",
  "credits": [
    {
      "name": "ReversingLabs",
      "contact": [
        "https://www.reversinglabs.com"
      ],
      "type": "FINDER"
    }
  ]
}