{
  "id": "MAL-2024-4991",
  "summary": "Malicious code in conio (PyPI)",
  "details": "\n---\n_-= Per source details. Do not edit below this line.=-_\n",
  "modified": "2024-06-25T13:34:13Z",
  "published": "2024-06-25T13:34:13Z",
  "database_specific": {
    "malicious-packages-origins": [
      {
        "modified_time": "2024-06-25T13:34:13Z",
        "import_time": "2024-06-28T02:48:41.578510747Z",
        "versions": [
          "0.0.1",
          "0.0.2",
          "0.0.4",
          "0.0.3"
        ],
        "id": "RLMA-2024-03771",
        "source": "reversing-labs",
        "sha256": "35ead6a5bc7d30eb94ad7e4690463a9833cceff4b1af4d047422738faced9d6d"
      }
    ]
  },
  "references": [
    {
      "type": "ADVISORY",
      "url": "https://research.jfrog.com/malicious-packages/"
    }
  ],
  "affected": [
    {
      "package": {
        "name": "conio",
        "ecosystem": "PyPI",
        "purl": "pkg:pypi/conio"
      },
      "versions": [
        "0.0.1",
        "0.0.2",
        "0.0.4",
        "0.0.3"
      ],
      "database_specific": {
        "source": "https://github.com/ossf/malicious-packages/blob/main/osv/malicious/pypi/conio/MAL-2024-4991.json"
      }
    }
  ],
  "schema_version": "1.6.0",
  "credits": [
    {
      "name": "ReversingLabs",
      "contact": [
        "https://www.reversinglabs.com"
      ],
      "type": "FINDER"
    }
  ]
}