{
  "id": "MAL-2024-5509",
  "summary": "Malicious code in pipcryptlibary (PyPI)",
  "details": "\n---\n_-= Per source details. Do not edit below this line.=-_\n",
  "aliases": [
    "SNYK-PYTHON-PIPCRYPTLIBARY-5932312"
  ],
  "modified": "2024-06-28T03:14:59.206429Z",
  "published": "2024-06-25T13:38:24Z",
  "database_specific": {
    "malicious-packages-origins": [
      {
        "modified_time": "2024-06-25T13:38:24Z",
        "import_time": "2024-06-28T02:49:42.668551748Z",
        "versions": [
          "1.1.0",
          "1.0.0"
        ],
        "id": "RLMA-2024-04291",
        "source": "reversing-labs",
        "sha256": "61ac1fe7e351e703bd038a59b4cc2bdde31a7164b9b13a7305719d3d18727e61"
      }
    ]
  },
  "references": [
    {
      "type": "ADVISORY",
      "url": "https://security.snyk.io/vuln/SNYK-PYTHON-PIPCRYPTLIBARY-5932312"
    },
    {
      "type": "ARTICLE",
      "url": "https://medium.com/checkmarx-security/the-evolutionary-tale-of-a-persistent-python-threat-d19196d4ed15"
    }
  ],
  "affected": [
    {
      "package": {
        "name": "pipcryptlibary",
        "ecosystem": "PyPI",
        "purl": "pkg:pypi/pipcryptlibary"
      },
      "versions": [
        "1.1.0",
        "1.0.0"
      ],
      "database_specific": {
        "source": "https://github.com/ossf/malicious-packages/blob/main/osv/malicious/pypi/pipcryptlibary/MAL-2024-5509.json"
      }
    }
  ],
  "schema_version": "1.6.0",
  "credits": [
    {
      "name": "ReversingLabs",
      "contact": [
        "https://www.reversinglabs.com"
      ],
      "type": "FINDER"
    }
  ]
}