{
  "id": "MAL-2024-5442",
  "summary": "Malicious code in p9llow (PyPI)",
  "details": "\n---\n_-= Per source details. Do not edit below this line.=-_\n",
  "modified": "2024-06-25T13:37:51Z",
  "published": "2024-06-25T13:37:51Z",
  "database_specific": {
    "malicious-packages-origins": [
      {
        "modified_time": "2024-06-25T13:37:51Z",
        "import_time": "2024-06-28T02:49:35.145850087Z",
        "versions": [
          "1.0.0"
        ],
        "id": "RLMA-2024-04224",
        "source": "reversing-labs",
        "sha256": "604bd96e8c82fd0cecf761dc49a0c75bde59e70a39beb68e31a34b10c02cd52a"
      }
    ]
  },
  "affected": [
    {
      "package": {
        "name": "p9llow",
        "ecosystem": "PyPI",
        "purl": "pkg:pypi/p9llow"
      },
      "versions": [
        "1.0.0"
      ],
      "database_specific": {
        "source": "https://github.com/ossf/malicious-packages/blob/main/osv/malicious/pypi/p9llow/MAL-2024-5442.json"
      }
    }
  ],
  "schema_version": "1.6.0",
  "credits": [
    {
      "name": "ReversingLabs",
      "contact": [
        "https://www.reversinglabs.com"
      ],
      "type": "FINDER"
    }
  ]
}