{
  "id": "MAL-2024-4746",
  "summary": "Malicious code in aicreator (PyPI)",
  "details": "\n---\n_-= Per source details. Do not edit below this line.=-_\n",
  "modified": "2024-06-25T13:32:14Z",
  "published": "2024-06-25T13:32:14Z",
  "database_specific": {
    "malicious-packages-origins": [
      {
        "modified_time": "2024-06-25T13:32:14Z",
        "import_time": "2024-06-28T02:48:13.711328701Z",
        "versions": [
          "0.2.0",
          "0.1.5",
          "0.2.5",
          "0.1.6",
          "0.2.4",
          "0.2.2",
          "0.2.3",
          "0.1.8",
          "0.1.9",
          "0.1.7"
        ],
        "id": "RLMA-2024-03526",
        "source": "reversing-labs",
        "sha256": "3ccf99c1a320a3dacfde2c9361a386a0598462b00f2160d73bba50a87729ecb5"
      }
    ]
  },
  "affected": [
    {
      "package": {
        "name": "aicreator",
        "ecosystem": "PyPI",
        "purl": "pkg:pypi/aicreator"
      },
      "versions": [
        "0.2.0",
        "0.1.5",
        "0.2.5",
        "0.1.6",
        "0.2.4",
        "0.2.2",
        "0.2.3",
        "0.1.8",
        "0.1.9",
        "0.1.7"
      ],
      "database_specific": {
        "source": "https://github.com/ossf/malicious-packages/blob/main/osv/malicious/pypi/aicreator/MAL-2024-4746.json"
      }
    }
  ],
  "schema_version": "1.6.0",
  "credits": [
    {
      "name": "ReversingLabs",
      "contact": [
        "https://www.reversinglabs.com"
      ],
      "type": "FINDER"
    }
  ]
}