{
  "id": "MAL-2024-5321",
  "summary": "Malicious code in libpesh (PyPI)",
  "details": "\n---\n_-= Per source details. Do not edit below this line.=-_\n",
  "modified": "2024-06-25T13:36:54Z",
  "published": "2024-06-25T13:36:54Z",
  "database_specific": {
    "malicious-packages-origins": [
      {
        "modified_time": "2024-06-25T13:36:54Z",
        "import_time": "2024-06-28T02:49:21.11914739Z",
        "versions": [
          "0.1"
        ],
        "id": "RLMA-2024-04103",
        "source": "reversing-labs",
        "sha256": "3e9e2ca6e63852d1dafe8225e5db265d303a2bd6ff42feb9f225d04bd231d433"
      }
    ]
  },
  "references": [
    {
      "type": "ARTICLE",
      "url": "https://blog.reversinglabs.com/blog/suppy-chain-malware-detecting-malware-in-package-manager-repositories"
    }
  ],
  "affected": [
    {
      "package": {
        "name": "libpesh",
        "ecosystem": "PyPI",
        "purl": "pkg:pypi/libpesh"
      },
      "versions": [
        "0.1"
      ],
      "database_specific": {
        "source": "https://github.com/ossf/malicious-packages/blob/main/osv/malicious/pypi/libpesh/MAL-2024-5321.json"
      }
    }
  ],
  "schema_version": "1.6.0",
  "credits": [
    {
      "name": "ReversingLabs",
      "contact": [
        "https://www.reversinglabs.com"
      ],
      "type": "FINDER"
    }
  ]
}